#!/usr/bin/env sh

yabai -m config layout                       float

# padding and gaps
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   20

# app rules
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^Digital Color Meter$" sticky=on

echo "yabai configuration loaded.."
